name: rtoken/utils Node.js Package

on:
  release:
    types: [created]

jobs:
  utils-publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: yarn build and publish
        working-directory: packages/utils
        run: |
          yarn bootstrap
          yarn build
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
