name: rtoken/utils Node.js Package

on:
  release:
    types: [created]

jobs:
  utils-publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: https://registry.npmjs.org/

      - name: yarn build and publish
        working-directory: packages/utils
        - run: yarn install
        - run: yarn build
        - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
